name: matrimony
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  get_storage: ^2.1.1
  get_it: any
  pinput: ^2.2.31
  numberpicker: ^2.1.2
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  connectivity_plus: any
  http: ^0.13.5
  share_plus: ^7.0.0
  scroll_date_picker: ^3.7.0
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  youtube_player_flutter: ^8.1.1
  flutter_windowmanager: ^0.2.0
  syncfusion_flutter_gauges: ^20.4.54
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.14
  dotted_border: 2.0.0+3
  url_launcher: ^6.1.11
  flutter: 
    sdk: flutter
  geocoding: ^2.1.0
  open_store: ^0.5.0
  geolocator: ^9.0.2
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.13.0
  firebase_messaging: ^14.2.1
  google_maps_place_picker_mb: ^3.0.2
  cloud_firestore: ^4.6.0
  google_maps_flutter: ^2.2.6
  syncfusion_flutter_pdfviewer: ^20.4.54
  razorpay_web: ^1.4.2
  google_mobile_ads: ^3.0.0
  intl_phone_field: ^3.1.0
  flutter_web_frame: ^1.0.0
  fluttertoast:

  #  Chat

  shared_preferences: ^2.1.0
  flutter_svg: ^1.1.5
  file_picker: ^5.2.0+1 #file picker
  package_info_plus: ^4.0.2 #package info
  permission_handler: ^10.2.0
  emoji_picker_flutter: ^1.4.0
  image_cropping: ^0.0.13 #crop image
  lottie: ^1.4.3
  custom_image_crop: ^0.0.4 #crop image
  photo_view: ^0.14.0
#  audioplayers: ^0.20.1
#  contacts_service: ^0.6.3
  focus_detector: ^2.0.1 #focus detector
  visibility_detector: 0.3.3
#  record: ^3.0.0
  swipe_to: ^1.0.2
  flutter_keyboard_visibility: ^5.4.0
  keyboard_dismisser: ^3.0.0
  scrollable_positioned_list: ^0.3.5 #scrollable position
  otp_text_field: ^1.1.3 #otp field
  firebase_app_installations: ^0.2.1+5 #firebase installations
  flutter_switch: ^0.3.2 #switchbox
  marquee: ^2.2.0 # marquee text
#  qr_code_scanner: ^1.0.1 #qr scanner
  yaml: ^3.1.1
  path: ^1.8.2
#  camera: ^0.10.5+2
#  video_player: ^2.6.1
  internet_connection_checker: ^1.0.0+1 # connectivity check
  provider: ^6.0.3
  photo_manager: ^2.6.0
  oktoast: ^3.3.1
  #  google_cloud_translation: ^0.0.3 # Google Translator
  flutter_inappwebview: ^5.7.2+3 # inapp webview
  flutter_libphonenumber: ^1.4.0
  open_file_plus: ^3.4.0
  is_lock_screen: ^2.0.0
  device_info_plus: ^8.1.0
  mirrorfly_plugin: ^0.0.10-beta
  firebase_analytics: ^10.4.4
  upgrader: ^6.5.0

dependency_overrides:
  visibility_detector: ^0.2.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/image/
    - assets/image/adsBanner/
    - assets/image/categories/
    - assets/image/credit_screen/
    - assets/image/editeProfile/
    - assets/image/HowAppWork/
    - assets/image/onBoardingScreen/
    - assets/image/otherProfile/
    - assets/image/PartnerPreferenceDetail/
    - assets/image/pictureprivacy/
    - assets/image/splash_screen/
    - assets/image/userprofile/
    - assets/countries.txt
    - assets/languages.txt
    - assets/logos/
    - assets/animation/
    - pubspec.yaml

  fonts:
    - family: Sora
      fonts: 
        - asset: assets/fonts/Sora-Regular.ttf
  uses-material-design: true

